name: "Simplecov Report"
description: "Simplecov Report"
author: nutrisense
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold
    default: 20
    required: false
  resultPath:
    description: "json path"
    default: "coverage.json"
    required: false
  token:
    description: "Github token"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
